#!/bin/bash
cd /root/src/RecommenderSystemImproved
hdfs dfs -rm -r /input
hdfs dfs -mkdir /input
hdfs dfs -put input/* /input
hdfs dfs -rm -r /dataDividedByUser
hdfs dfs -rm -r /EstimateRating 
hdfs dfs -rm -r /coOccurrenceMatrix
hdfs dfs -rm -r /Normalize
hdfs dfs -rm -r /Multiplication
hdfs dfs -rm -r /Sum
cd src/main/java/
hadoop com.sun.tools.javac.Main *.java
jar cf recommender.jar *.class
hadoop jar recommender.jar Driver /input/userRating.txt /input /dataDividedByUser /EstimateRating /coOccurrenceMatrix /Normalize /Multiplication /Sum
cd ../../../
rm dataDividedByUser
rm EstimateRating
rm coOccurrenceMatrix
rm Normalize
rm Multiplication
rm Sum
hdfs dfs -cat /dataDividedByUser/* dataDividedByUser
hdfs dfs -cat /EstimateRating/* EstimateRating
hdfs dfs -cat /coOccurrenceMatrix/* coOccurrenceMatrix
hdfs dfs -cat /Normalize/* Normalize
hdfs dfs -cat /Multiplication/* Multiplication
hdfs dfs -cat /Sum/* Sum
